version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      prisma:
        patterns:
          - "@prisma/client"
          - "prisma"
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
