volumes:
  db_data:

services:
  db:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 10
  jetstream:
    image: ghcr.io/bluesky-social/jetstream:sha-011b545
    restart: always
    network_mode: host
    environment:
      - JETSTREAM_WS_URL=ws://localhost:2583/xrpc/com.atproto.sync.subscribeRepos
      - JETSTREAM_WORKER_COUNT=1
