# fly.toml app configuration file generated for linkat on 2024-09-03T00:58:29+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'linkat-stg'
primary_region = 'nrt'

[build]

[deploy]
release_command = 'npx prisma db push --skip-generate'
strategy = 'bluegreen'

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'suspend'
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[[http_service.checks]]
interval = '2s'
timeout = '2s'
grace_period = '5s'
method = 'GET'
path = '/health'

[[vm]]
size = 'shared-cpu-1x'
memory = "512mb"
