name: Lexicon

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lex-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: mkizka/lex-publish@v1
        with:
          lint: false
          publish: ${{ github.ref == 'refs/heads/main' }}
        env:
          GOAT_USERNAME: ${{ secrets.GOAT_USERNAME }}
          GOAT_PASSWORD: ${{ secrets.GOAT_PASSWORD }}
