name: Lexicon

on:
  push:
    branches:
      - main
    paths:
      - lexicons/blue/linkat/**
      - .github/workflows/lexicon.yml
  pull_request:
    paths:
      - lexicons/blue/linkat/**
      - .github/workflows/lexicon.yml

jobs:
  lex-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: mkizka/lex-publish@e65d2b1b5ac79fd074a1aaf0eb59d67162cd9e9f # v2.0.0
        with:
          paths: lexicons/blue/linkat
          lint: false
          publish: ${{ github.ref == 'refs/heads/main' }}
          username: ${{ secrets.GOAT_USERNAME }}
          password: ${{ secrets.GOAT_PASSWORD }}
